# Generated by Django 6.1.1 on 2026-10-01 11:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('developer', models.CharField(blank=True, max_length=150)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('off_plan', 'Off-plan'), ('under_construction', 'Under construction'), ('completed', 'Completed')], default='off_plan', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('video_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.area')),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.neighbourhood')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Photo'), ('floor_plan', 'Floor plan'), ('video', 'Video')], default='image', max_length=20)),
                ('public_id', models.CharField(help_text='Cloudinary public ID', max_length=255)),
                ('resource_type', models.CharField(default='image', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Describe the photo for screen readers and SEO.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
            ],
            options={
                'verbose_name': 'photo / file',
                'verbose_name_plural': 'photos & files',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2 Bedroom Apartment', max_length=100)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_sqm_min', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('size_sqm_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('price_from', models.PositiveBigIntegerField(blank=True, help_text='KES', null=True)),
                ('price_to', models.PositiveBigIntegerField(blank=True, help_text='KES', null=True)),
                ('units_available', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'bedrooms', 'id'],
            },
        ),
    ]
