# Generated by Django 6.1.1 on 2026-10-01 11:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('group', models.CharField(blank=True, help_text='e.g. Security, Utilities', max_length=40)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('deal_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'Commercial Lease')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('under_offer', 'Under offer'), ('sold', 'Sold'), ('let', 'Let'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('price', models.PositiveBigIntegerField(blank=True, help_text='KES', null=True)),
                ('price_unit', models.CharField(choices=[('total', 'Total'), ('per_month', 'per month'), ('per_sqm', 'per m²'), ('per_sqft', 'per ft²'), ('per_acre', 'per acre')], default='total', max_length=10)),
                ('price_on_request', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('built_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('land_area_unit', models.CharField(choices=[('acres', 'acres'), ('hectares', 'hectares'), ('sqm', 'm²')], default='acres', max_length=10)),
                ('furnishing', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi-furnished'), ('furnished', 'Furnished')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('show_exact_location', models.BooleanField(default=False, help_text='Otherwise the public map shows an approximate position.')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo link')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('agent', models.ForeignKey(blank=True, help_text='Staff contact shown on the listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.area')),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.neighbourhood')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='projects.project')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.propertytype')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Photo'), ('floor_plan', 'Floor plan'), ('video', 'Video')], default='image', max_length=20)),
                ('public_id', models.CharField(help_text='Cloudinary public ID', max_length=255)),
                ('resource_type', models.CharField(default='image', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Describe the photo for screen readers and SEO.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.property')),
            ],
            options={
                'verbose_name': 'photo / file',
                'verbose_name_plural': 'photos & files',
                'ordering': ['order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['property', 'kind', 'order'], name='listings_pr_propert_5a8879_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'deal_type', '-published_at'], name='listings_pr_status_4f73f2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'price'], name='listings_pr_status_30a50b_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price_on_request', True), ('price__isnull', False), _connector='OR'), name='price_required_unless_on_request'),
        ),
    ]
