# Generated by Django 6.1.1 on 2026-10-02 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='shown on the website')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('general', 'General'), ('buying', 'Buying and renting'), ('selling', 'Selling and letting'), ('management', 'Property management'), ('valuation', 'Valuations'), ('assets', 'Asset management'), ('survey', 'Land surveys')], db_index=True, default='general', max_length=20)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('location', models.CharField(default='Westlands, Nairobi', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('internship', 'Internship or attachment')], default='full_time', max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='Rich text, sanitised on save.')),
                ('apply_email', models.EmailField(default='info@alcomconsultants.co.ke', max_length=254)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'job opening',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='shown on the website')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. "Registered Valuer"', max_length=120)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('photo_public_id', models.CharField(blank=True, max_length=255)),
                ('photo_width', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_height', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, help_text='Shown publicly if set.', max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'team member',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='shown on the website')),
                ('quote', models.TextField(max_length=800)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text='e.g. "Landlord, Kilimani"', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars', null=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
