# Generated by Django 6.1.1 on 2026-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, help_text="The visitor's own choice.", verbose_name='news and offers by email'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in_at',
            field=models.DateTimeField(blank=True, help_text='When the visitor last opted in (consent record).', null=True),
        ),
    ]
