# Generated by Django 6.1.1 on 2026-10-01 11:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(help_text='Official county code (1-47)', unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Approximate centre, used to centre maps', null=True, srid=4326)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='locations.county')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighbourhoods', to='locations.area')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('county', 'slug'), name='unique_area_slug_per_county'),
        ),
        migrations.AddConstraint(
            model_name='neighbourhood',
            constraint=models.UniqueConstraint(fields=('area', 'slug'), name='unique_neighbourhood_slug_per_area'),
        ),
    ]
