import createClient, { type Middleware } from "openapi-fetch";

import { withCsrf } from "./csrf";
import type { paths } from "./schema";

const csrf: Middleware = {
  onRequest({ request }) {
    withCsrf(request.method, request.headers);
    return request;
  },
};

/**
 * Typed client for the Django API (types generated by `make api-types`).
 * Same origin as the site, so the session cookie is sent automatically.
 */
export const api = createClient<paths>({
  baseUrl: "",
  credentials: "same-origin",
});
api.use(csrf);

export class ApiError extends Error {
  constructor(
    public status: number,
    message = `Request failed (${status})`,
  ) {
    super(message);
  }
}

/** Unwrap an openapi-fetch result, throwing ApiError on failure (for React Query). */
export function unwrap<T>(result: {
  data?: T;
  error?: unknown;
  response: Response;
}): T {
  if (result.error !== undefined || result.data === undefined) {
    throw new ApiError(result.response.status);
  }
  return result.data;
}
