/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/amenities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["amenities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Headline numbers for the dashboard home page. */
        get: operations["dashboard_overview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness/readiness probe used by Docker, Nginx upstream checks and uptime monitors. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All counties with their areas (for location pickers). */
        get: operations["locations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Autocomplete across counties, areas and neighbourhoods (`?q=kili`). */
        get: operations["locations_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The signed-in user (403 when signed out). */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public listings. Search shows active listings; sold/let pages stay reachable. */
        get: operations["properties_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public listings. Search shows active listings; sold/let pages stay reachable. */
        get: operations["properties_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/property-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["property_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agent: {
            name: string;
            phone: string;
            /** Format: email */
            email: string;
        };
        Amenity: {
            name: string;
            slug: string;
            /** @description e.g. Security, Utilities */
            group?: string;
            /** @description Lucide icon name */
            icon?: string;
        };
        Area: {
            name: string;
            slug: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `residential` - Residential
         *     * `commercial` - Commercial
         *     * `land` - Land
         * @enum {string}
         */
        CategoryEnum: "residential" | "commercial" | "land";
        CountyTree: {
            /** @description Official county code (1-47) */
            code: number;
            name: string;
            slug: string;
            readonly areas: components["schemas"]["Area"][];
        };
        DashboardOverview: {
            listed: number;
            drafts: number;
            under_offer: number;
            closed: number;
            featured: number;
        };
        /**
         * @description * `sale` - For Sale
         *     * `rent` - For Rent
         *     * `lease` - Commercial Lease
         * @enum {string}
         */
        DealTypeEnum: "sale" | "rent" | "lease";
        /**
         * @description * `unfurnished` - Unfurnished
         *     * `semi` - Semi-furnished
         *     * `furnished` - Furnished
         * @enum {string}
         */
        FurnishingEnum: "unfurnished" | "semi" | "furnished";
        Health: {
            status: string;
            database: boolean;
            cache: boolean;
        };
        /**
         * @description * `county` - county
         *     * `area` - area
         *     * `neighbourhood` - neighbourhood
         * @enum {string}
         */
        KindEnum: "county" | "area" | "neighbourhood";
        /**
         * @description * `acres` - acres
         *     * `hectares` - hectares
         *     * `sqm` - m²
         * @enum {string}
         */
        LandAreaUnitEnum: "acres" | "hectares" | "sqm";
        Location: {
            county: string;
            county_slug: string;
            area: string;
            area_slug: string;
            /** @default  */
            neighbourhood: string;
            /** @default  */
            neighbourhood_slug: string;
            /** Format: double */
            readonly lat: number | null;
            /** Format: double */
            readonly lng: number | null;
            readonly is_exact: boolean;
        };
        /** @description One autocomplete suggestion; `text` is what the user sees. */
        LocationMatch: {
            kind: components["schemas"]["KindEnum"];
            text: string;
            county: string;
            area: string;
            neighbourhood: string;
        };
        Me: {
            /**
             * Email address
             * Format: email
             */
            email: string;
            first_name?: string;
            last_name?: string;
            full_name: string;
            phone?: string;
            /** @description Designates whether the user can access the staff dashboard. */
            is_staff?: boolean;
            readonly mfa_enabled: boolean;
        };
        /** @description Cloudinary asset. Clients build sized URLs from `public_id`; `url` is the original. */
        Media: {
            public_id: string;
            kind: string;
            resource_type: string;
            url: string;
            width: number | null;
            height: number | null;
            alt_text: string;
            caption: string;
        };
        PaginatedProjectListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectList"][];
        };
        PaginatedPropertyListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PropertyList"][];
        };
        /**
         * @description * `total` - Total
         *     * `per_month` - per month
         *     * `per_sqm` - per m²
         *     * `per_sqft` - per ft²
         *     * `per_acre` - per acre
         * @enum {string}
         */
        PriceUnitEnum: "total" | "per_month" | "per_sqm" | "per_sqft" | "per_acre";
        ProjectDetail: {
            slug?: string;
            name: string;
            developer?: string;
            summary: string;
            status?: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            completion_date?: string | null;
            county: string;
            area: string;
            readonly cover_image: components["schemas"]["Media"] | null;
            readonly price_from: number | null;
            is_featured?: boolean;
            description: string;
            video_url?: string;
            readonly unit_types: components["schemas"]["UnitType"][];
            readonly updates: components["schemas"]["ProjectUpdate"][];
            readonly media: components["schemas"]["Media"][];
        };
        ProjectList: {
            slug?: string;
            name: string;
            developer?: string;
            summary: string;
            status?: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            completion_date?: string | null;
            county: string;
            area: string;
            readonly cover_image: components["schemas"]["Media"] | null;
            readonly price_from: number | null;
            is_featured?: boolean;
        };
        /**
         * @description * `off_plan` - Off-plan
         *     * `under_construction` - Under construction
         *     * `completed` - Completed
         * @enum {string}
         */
        ProjectStatusEnum: "off_plan" | "under_construction" | "completed";
        ProjectUpdate: {
            /** Format: date */
            date: string;
            title: string;
            body?: string;
        };
        PropertyDetail: {
            readonly reference: string | null;
            readonly slug: string;
            title: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            status?: components["schemas"]["PropertyStatusEnum"];
            readonly property_type: components["schemas"]["PropertyType"];
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            readonly location: components["schemas"]["Location"];
            readonly cover_image: components["schemas"]["Media"] | null;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            description: string;
            parking_spaces?: number | null;
            furnishing?: components["schemas"]["FurnishingEnum"] | components["schemas"]["BlankEnum"];
            readonly amenities: components["schemas"]["Amenity"][];
            readonly media: components["schemas"]["Media"][];
            /** @description YouTube or Vimeo link */
            video_url?: string;
            readonly agent: components["schemas"]["Agent"] | null;
            readonly project: {
                name?: string;
                slug?: string;
            } | null;
            seo_title?: string;
            seo_description?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PropertyList: {
            readonly reference: string | null;
            readonly slug: string;
            title: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            status?: components["schemas"]["PropertyStatusEnum"];
            readonly property_type: components["schemas"]["PropertyType"];
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            readonly location: components["schemas"]["Location"];
            readonly cover_image: components["schemas"]["Media"] | null;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
        };
        /**
         * @description * `draft` - Draft
         *     * `published` - Published
         *     * `under_offer` - Under offer
         *     * `sold` - Sold
         *     * `let` - Let
         *     * `archived` - Archived
         * @enum {string}
         */
        PropertyStatusEnum: "draft" | "published" | "under_offer" | "sold" | "let" | "archived";
        PropertyType: {
            name: string;
            slug: string;
            category: components["schemas"]["CategoryEnum"];
        };
        UnitType: {
            /** @description e.g. 2 Bedroom Apartment */
            name: string;
            bedrooms?: number | null;
            /** Format: decimal */
            size_sqm_min?: string | null;
            /** Format: decimal */
            size_sqm_max?: string | null;
            /**
             * Format: int64
             * @description KES
             */
            price_from?: number | null;
            /**
             * Format: int64
             * @description KES
             */
            price_to?: number | null;
            units_available?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    amenities_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amenity"][];
                };
            };
        };
    };
    dashboard_overview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverview"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    locations_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountyTree"][];
                };
            };
        };
    };
    locations_search_list: {
        parameters: {
            query: {
                /** @description At least 2 letters */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationMatch"][];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    projects_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectListList"];
                };
            };
        };
    };
    projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    properties_list: {
        parameters: {
            query?: {
                /** @description Must have all of: ?amenities=gym,lift */
                amenities?: string;
                /** @description Multiple values may be separated by commas. */
                area?: string[];
                county?: string;
                /**
                 * @description * `sale` - For Sale
                 *     * `rent` - For Rent
                 *     * `lease` - Commercial Lease
                 */
                deal?: "lease" | "rent" | "sale";
                featured?: boolean;
                /**
                 * @description * `unfurnished` - Unfurnished
                 *     * `semi` - Semi-furnished
                 *     * `furnished` - Furnished
                 */
                furnishing?: "furnished" | "semi" | "unfurnished";
                max_price?: number;
                min_baths?: number;
                min_beds?: number;
                min_price?: number;
                /** @description Multiple values may be separated by commas. */
                neighbourhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Keyword, reference or place name */
                q?: string;
                /**
                 * @description * `newest` - Newest
                 *     * `price_asc` - Price: low to high
                 *     * `price_desc` - Price: high to low
                 */
                sort?: "newest" | "price_asc" | "price_desc";
                /** @description Multiple values may be separated by commas. */
                type?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPropertyListList"];
                };
            };
        };
    };
    properties_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
        };
    };
    property_types_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyType"][];
                };
            };
        };
    };
}
