/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/amenities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["amenities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/lookups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Everything the listing form needs, in one request. */
        get: operations["dashboard_lookups_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Headline numbers for the dashboard (also used for the status tabs). */
        get: operations["dashboard_overview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Staff listing management. Published listings are archived, not deleted. */
        get: operations["dashboard_properties_list"];
        put?: never;
        /** @description Staff listing management. Published listings are archived, not deleted. */
        post: operations["dashboard_properties_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/properties/{property_uuid}/media/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Photos and floor plans of one listing, in display order (first = cover). */
        get: operations["dashboard_properties_media_list"];
        put?: never;
        /** @description Photos and floor plans of one listing, in display order (first = cover). */
        post: operations["dashboard_properties_media_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/properties/{property_uuid}/media/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Photos and floor plans of one listing, in display order (first = cover). */
        delete: operations["dashboard_properties_media_destroy"];
        options?: never;
        head?: never;
        /** @description Photos and floor plans of one listing, in display order (first = cover). */
        patch: operations["dashboard_properties_media_partial_update"];
        trace?: never;
    };
    "/api/v1/dashboard/properties/{property_uuid}/media/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Photos and floor plans of one listing, in display order (first = cover). */
        post: operations["dashboard_properties_media_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/properties/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Staff listing management. Published listings are archived, not deleted. */
        get: operations["dashboard_properties_retrieve"];
        put?: never;
        post?: never;
        /** @description Staff listing management. Published listings are archived, not deleted. */
        delete: operations["dashboard_properties_destroy"];
        options?: never;
        head?: never;
        /** @description Staff listing management. Published listings are archived, not deleted. */
        patch: operations["dashboard_properties_partial_update"];
        trace?: never;
    };
    "/api/v1/dashboard/uploads/signature/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Signed parameters for one direct browser → Cloudinary upload. */
        post: operations["dashboard_uploads_signature_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness/readiness probe used by Docker, Nginx upstream checks and uptime monitors. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All counties with their areas (for location pickers). */
        get: operations["locations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Autocomplete across counties, areas and neighbourhoods (`?q=kili`). */
        get: operations["locations_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The signed-in user (403 when signed out). */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projects_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public listings. Search shows active listings; sold/let pages stay reachable. */
        get: operations["properties_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public listings. Search shows active listings; sold/let pages stay reachable. */
        get: operations["properties_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{slug}/nearby/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Schools, health, shopping, transport and parks within 1.5 km (OpenStreetMap). */
        get: operations["properties_nearby_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{slug}/similar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Up to 4 listings like this one: same deal, then same area/type, closest price. */
        get: operations["properties_similar_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/map/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every matching listing as a map marker (same filters as the list, max 500). */
        get: operations["properties_map_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/property-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["property_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agent: {
            name: string;
            phone: string;
            /** Format: email */
            email: string;
        };
        Amenity: {
            name: string;
            slug: string;
            /** @description e.g. Security, Utilities */
            group?: string;
            /** @description Lucide icon name */
            icon?: string;
        };
        Area: {
            name: string;
            slug: string;
        };
        /**
         * @description * `image` - image
         *     * `floor_plan` - floor_plan
         * @enum {string}
         */
        AttachUploadKindEnum: "image" | "floor_plan";
        /** @description The upload result Cloudinary returned to the browser. */
        AttachUploadRequest: {
            public_id: string;
            version: number;
            signature: string;
            width?: number | null;
            height?: number | null;
            bytes?: number | null;
            format?: string;
            /** @default image */
            kind: components["schemas"]["AttachUploadKindEnum"];
            alt_text?: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `residential` - Residential
         *     * `commercial` - Commercial
         *     * `land` - Land
         * @enum {string}
         */
        CategoryEnum: "residential" | "commercial" | "land";
        CountyTree: {
            /** @description Official county code (1-47) */
            code: number;
            name: string;
            slug: string;
            readonly areas: components["schemas"]["Area"][];
        };
        DashboardOverview: {
            total: number;
            listed: number;
            drafts: number;
            under_offer: number;
            closed: number;
            archived: number;
            featured: number;
        };
        /** @description Create / edit a listing. */
        DashboardProperty: {
            /** Format: uuid */
            readonly uuid: string;
            readonly reference: string | null;
            readonly slug: string;
            status?: components["schemas"]["PropertyStatusEnum"];
            title: string;
            description: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            property_type: string;
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            parking_spaces?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            furnishing?: components["schemas"]["FurnishingEnum"] | components["schemas"]["BlankEnum"];
            amenities?: string[];
            readonly county: number;
            area: number;
            neighbourhood?: number | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            /** @description Otherwise the public map shows an approximate position. */
            show_exact_location?: boolean;
            agent?: number | null;
            project?: number | null;
            /** @description YouTube or Vimeo link */
            video_url?: string;
            is_featured?: boolean;
            seo_title?: string;
            seo_description?: string;
            /** Format: date-time */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly created_by: string | null;
            readonly updated_by: string | null;
        };
        DashboardPropertyList: {
            /** Format: uuid */
            readonly uuid: string;
            readonly reference: string | null;
            readonly slug: string;
            title: string;
            status?: components["schemas"]["PropertyStatusEnum"];
            deal_type: components["schemas"]["DealTypeEnum"];
            property_type: string;
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            readonly location: string;
            readonly cover_image: string | null;
            readonly photo_count: number;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Create / edit a listing. */
        DashboardPropertyRequest: {
            status?: components["schemas"]["PropertyStatusEnum"];
            title: string;
            description: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            property_type: string;
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            parking_spaces?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            furnishing?: components["schemas"]["FurnishingEnum"] | components["schemas"]["BlankEnum"];
            amenities?: string[];
            area: number;
            neighbourhood?: number | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            /** @description Otherwise the public map shows an approximate position. */
            show_exact_location?: boolean;
            agent?: number | null;
            project?: number | null;
            /** @description YouTube or Vimeo link */
            video_url?: string;
            is_featured?: boolean;
            seo_title?: string;
            seo_description?: string;
        };
        /**
         * @description * `sale` - For Sale
         *     * `rent` - For Rent
         *     * `lease` - Commercial Lease
         * @enum {string}
         */
        DealTypeEnum: "sale" | "rent" | "lease";
        /**
         * @description * `unfurnished` - Unfurnished
         *     * `semi` - Semi-furnished
         *     * `furnished` - Furnished
         * @enum {string}
         */
        FurnishingEnum: "unfurnished" | "semi" | "furnished";
        Health: {
            status: string;
            database: boolean;
            cache: boolean;
        };
        /**
         * @description * `acres` - acres
         *     * `hectares` - hectares
         *     * `sqm` - m²
         * @enum {string}
         */
        LandAreaUnitEnum: "acres" | "hectares" | "sqm";
        Location: {
            county: string;
            county_slug: string;
            area: string;
            area_slug: string;
            /** @default  */
            neighbourhood: string;
            /** @default  */
            neighbourhood_slug: string;
            /** Format: double */
            readonly lat: number | null;
            /** Format: double */
            readonly lng: number | null;
            readonly is_exact: boolean;
        };
        /** @description One autocomplete suggestion; `text` is what the user sees. */
        LocationMatch: {
            kind: components["schemas"]["LocationMatchKindEnum"];
            text: string;
            county: string;
            area: string;
            neighbourhood: string;
        };
        /**
         * @description * `county` - county
         *     * `area` - area
         *     * `neighbourhood` - neighbourhood
         * @enum {string}
         */
        LocationMatchKindEnum: "county" | "area" | "neighbourhood";
        Lookups: {
            property_types: components["schemas"]["_Choice"][];
            amenities: components["schemas"]["_Choice"][];
            counties: components["schemas"]["_CountyLookup"][];
            agents: components["schemas"]["_Agent"][];
            projects: components["schemas"]["_NamedId"][];
        };
        /** @description Lightweight marker for the search map. */
        MapPoint: {
            readonly reference: string | null;
            readonly slug: string;
            title: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            /** Format: double */
            readonly lat: number | null;
            /** Format: double */
            readonly lng: number | null;
            readonly cover_image: string | null;
        };
        Me: {
            /**
             * Email address
             * Format: email
             */
            email: string;
            first_name?: string;
            last_name?: string;
            full_name: string;
            phone?: string;
            /** @description Designates whether the user can access the staff dashboard. */
            is_staff?: boolean;
            readonly mfa_enabled: boolean;
        };
        /** @description Cloudinary asset. Clients build sized URLs from `public_id`; `url` is the original. */
        Media: {
            public_id: string;
            kind: string;
            resource_type: string;
            url: string;
            width: number | null;
            height: number | null;
            alt_text: string;
            caption: string;
        };
        NearbyGroup: {
            category: string;
            places: components["schemas"]["NearbyPlace"][];
        };
        NearbyPlace: {
            name: string;
            type: string;
            distance_m: number;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        PaginatedDashboardPropertyListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DashboardPropertyList"][];
        };
        PaginatedProjectListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectList"][];
        };
        PaginatedPropertyListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PropertyList"][];
        };
        /** @description Create / edit a listing. */
        PatchedDashboardPropertyRequest: {
            status?: components["schemas"]["PropertyStatusEnum"];
            title?: string;
            description?: string;
            deal_type?: components["schemas"]["DealTypeEnum"];
            property_type?: string;
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            parking_spaces?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            furnishing?: components["schemas"]["FurnishingEnum"] | components["schemas"]["BlankEnum"];
            amenities?: string[];
            area?: number;
            neighbourhood?: number | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            /** @description Otherwise the public map shows an approximate position. */
            show_exact_location?: boolean;
            agent?: number | null;
            project?: number | null;
            /** @description YouTube or Vimeo link */
            video_url?: string;
            is_featured?: boolean;
            seo_title?: string;
            seo_description?: string;
        };
        PatchedPropertyMediaRequest: {
            kind?: components["schemas"]["PropertyMediaKindEnum"];
            /** @description Describe the photo for screen readers and SEO. */
            alt_text?: string;
            caption?: string;
        };
        /**
         * @description * `total` - Total
         *     * `per_month` - per month
         *     * `per_sqm` - per m²
         *     * `per_sqft` - per ft²
         *     * `per_acre` - per acre
         * @enum {string}
         */
        PriceUnitEnum: "total" | "per_month" | "per_sqm" | "per_sqft" | "per_acre";
        ProjectDetail: {
            slug?: string;
            name: string;
            developer?: string;
            summary: string;
            status?: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            completion_date?: string | null;
            county: string;
            area: string;
            readonly cover_image: components["schemas"]["Media"] | null;
            readonly price_from: number | null;
            is_featured?: boolean;
            description: string;
            video_url?: string;
            readonly unit_types: components["schemas"]["UnitType"][];
            readonly updates: components["schemas"]["ProjectUpdate"][];
            readonly media: components["schemas"]["Media"][];
        };
        ProjectList: {
            slug?: string;
            name: string;
            developer?: string;
            summary: string;
            status?: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            completion_date?: string | null;
            county: string;
            area: string;
            readonly cover_image: components["schemas"]["Media"] | null;
            readonly price_from: number | null;
            is_featured?: boolean;
        };
        /**
         * @description * `off_plan` - Off-plan
         *     * `under_construction` - Under construction
         *     * `completed` - Completed
         * @enum {string}
         */
        ProjectStatusEnum: "off_plan" | "under_construction" | "completed";
        ProjectUpdate: {
            /** Format: date */
            date: string;
            title: string;
            body?: string;
        };
        PropertyDetail: {
            readonly reference: string | null;
            readonly slug: string;
            title: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            status?: components["schemas"]["PropertyStatusEnum"];
            readonly property_type: components["schemas"]["PropertyType"];
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            readonly location: components["schemas"]["Location"];
            readonly cover_image: components["schemas"]["Media"] | null;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            description: string;
            parking_spaces?: number | null;
            furnishing?: components["schemas"]["FurnishingEnum"] | components["schemas"]["BlankEnum"];
            readonly amenities: components["schemas"]["Amenity"][];
            readonly media: components["schemas"]["Media"][];
            /** @description YouTube or Vimeo link */
            video_url?: string;
            readonly agent: components["schemas"]["Agent"] | null;
            readonly project: {
                name?: string;
                slug?: string;
            } | null;
            seo_title?: string;
            seo_description?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PropertyList: {
            readonly reference: string | null;
            readonly slug: string;
            title: string;
            deal_type: components["schemas"]["DealTypeEnum"];
            status?: components["schemas"]["PropertyStatusEnum"];
            readonly property_type: components["schemas"]["PropertyType"];
            /**
             * Format: int64
             * @description KES
             */
            price?: number | null;
            price_unit?: components["schemas"]["PriceUnitEnum"];
            price_on_request?: boolean;
            bedrooms?: number | null;
            bathrooms?: number | null;
            /** Format: decimal */
            built_area_sqm?: string | null;
            /** Format: decimal */
            land_area?: string | null;
            land_area_unit?: components["schemas"]["LandAreaUnitEnum"];
            readonly location: components["schemas"]["Location"];
            readonly cover_image: components["schemas"]["Media"] | null;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
        };
        PropertyMedia: {
            readonly id: number;
            /** @description Cloudinary public ID */
            readonly public_id: string;
            kind?: components["schemas"]["PropertyMediaKindEnum"];
            readonly url: string;
            readonly width: number | null;
            readonly height: number | null;
            readonly bytes: number | null;
            readonly format: string;
            /** @description Describe the photo for screen readers and SEO. */
            alt_text?: string;
            caption?: string;
            readonly order: number;
        };
        /**
         * @description * `image` - Photo
         *     * `floor_plan` - Floor plan
         *     * `video` - Video
         * @enum {string}
         */
        PropertyMediaKindEnum: "image" | "floor_plan" | "video";
        /**
         * @description * `draft` - Draft
         *     * `published` - Published
         *     * `under_offer` - Under offer
         *     * `sold` - Sold
         *     * `let` - Let
         *     * `archived` - Archived
         * @enum {string}
         */
        PropertyStatusEnum: "draft" | "published" | "under_offer" | "sold" | "let" | "archived";
        PropertyType: {
            name: string;
            slug: string;
            category: components["schemas"]["CategoryEnum"];
        };
        ReorderRequest: {
            ids: number[];
        };
        /**
         * @description * `projects` - projects
         *     * `properties` - properties
         * @enum {string}
         */
        TargetEnum: "projects" | "properties";
        UnitType: {
            /** @description e.g. 2 Bedroom Apartment */
            name: string;
            bedrooms?: number | null;
            /** Format: decimal */
            size_sqm_min?: string | null;
            /** Format: decimal */
            size_sqm_max?: string | null;
            /**
             * Format: int64
             * @description KES
             */
            price_from?: number | null;
            /**
             * Format: int64
             * @description KES
             */
            price_to?: number | null;
            units_available?: number | null;
        };
        UploadSignature: {
            /** Format: uri */
            upload_url: string;
            api_key: string;
            cloud_name: string;
            timestamp: number;
            folder: string;
            allowed_formats: string;
            signature: string;
            max_bytes: number;
        };
        UploadSignatureRequestRequest: {
            target: components["schemas"]["TargetEnum"];
        };
        _Agent: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
        };
        _AreaLookup: {
            id: number;
            name: string;
            neighbourhoods: components["schemas"]["_NamedId"][];
        };
        _Choice: {
            slug: string;
            name: string;
            group: string;
        };
        _CountyLookup: {
            id: number;
            name: string;
            areas: components["schemas"]["_AreaLookup"][];
        };
        _NamedId: {
            id: number;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    amenities_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amenity"][];
                };
            };
        };
    };
    dashboard_lookups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lookups"];
                };
            };
        };
    };
    dashboard_overview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverview"];
                };
            };
        };
    };
    dashboard_properties_list: {
        parameters: {
            query?: {
                /**
                 * @description * `sale` - For Sale
                 *     * `rent` - For Rent
                 *     * `lease` - Commercial Lease
                 */
                deal?: "lease" | "rent" | "sale";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                q?: string;
                /**
                 * @description Ordering
                 *
                 *     * `updated` - Updated
                 *     * `-updated` - Updated (descending)
                 *     * `created` - Created
                 *     * `-created` - Created (descending)
                 *     * `price` - Price
                 *     * `-price` - Price (descending)
                 *     * `title` - Title
                 *     * `-title` - Title (descending)
                 */
                sort?: ("-created" | "-price" | "-title" | "-updated" | "created" | "price" | "title" | "updated")[];
                /**
                 * @description * `draft` - Draft
                 *     * `published` - Published
                 *     * `under_offer` - Under offer
                 *     * `sold` - Sold
                 *     * `let` - Let
                 *     * `archived` - Archived
                 *     * `closed` - Sold or let
                 */
                status?: "archived" | "closed" | "draft" | "let" | "published" | "sold" | "under_offer";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDashboardPropertyListList"];
                };
            };
        };
    };
    dashboard_properties_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardPropertyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DashboardPropertyRequest"];
                "multipart/form-data": components["schemas"]["DashboardPropertyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProperty"];
                };
            };
        };
    };
    dashboard_properties_media_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path: {
                property_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyMedia"][];
                };
            };
        };
    };
    dashboard_properties_media_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachUploadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AttachUploadRequest"];
                "multipart/form-data": components["schemas"]["AttachUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyMedia"];
                };
            };
        };
    };
    dashboard_properties_media_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this photo / file. */
                id: number;
                property_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_properties_media_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this photo / file. */
                id: number;
                property_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPropertyMediaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPropertyMediaRequest"];
                "multipart/form-data": components["schemas"]["PatchedPropertyMediaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyMedia"];
                };
            };
        };
    };
    dashboard_properties_media_reorder_create: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path: {
                property_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReorderRequest"];
                "multipart/form-data": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyMedia"][];
                };
            };
        };
    };
    dashboard_properties_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProperty"];
                };
            };
        };
    };
    dashboard_properties_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_properties_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDashboardPropertyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDashboardPropertyRequest"];
                "multipart/form-data": components["schemas"]["PatchedDashboardPropertyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProperty"];
                };
            };
        };
    };
    dashboard_uploads_signature_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSignatureRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadSignatureRequestRequest"];
                "multipart/form-data": components["schemas"]["UploadSignatureRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignature"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    locations_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountyTree"][];
                };
            };
        };
    };
    locations_search_list: {
        parameters: {
            query: {
                /** @description At least 2 letters */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationMatch"][];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    projects_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectListList"];
                };
            };
        };
    };
    projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    properties_list: {
        parameters: {
            query?: {
                /** @description Must have all of: ?amenities=gym,lift */
                amenities?: string;
                /** @description Multiple values may be separated by commas. */
                area?: string[];
                /** @description Map area: min_lng,min_lat,max_lng,max_lat */
                bbox?: string;
                county?: string;
                /**
                 * @description * `sale` - For Sale
                 *     * `rent` - For Rent
                 *     * `lease` - Commercial Lease
                 */
                deal?: "lease" | "rent" | "sale";
                featured?: boolean;
                /**
                 * @description * `unfurnished` - Unfurnished
                 *     * `semi` - Semi-furnished
                 *     * `furnished` - Furnished
                 */
                furnishing?: "furnished" | "semi" | "unfurnished";
                max_price?: number;
                min_baths?: number;
                min_beds?: number;
                min_price?: number;
                /** @description Multiple values may be separated by commas. */
                neighbourhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Keyword, reference or place name */
                q?: string;
                /**
                 * @description * `newest` - Newest
                 *     * `price_asc` - Price: low to high
                 *     * `price_desc` - Price: high to low
                 */
                sort?: "newest" | "price_asc" | "price_desc";
                /** @description Multiple values may be separated by commas. */
                type?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPropertyListList"];
                };
            };
        };
    };
    properties_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
        };
    };
    properties_nearby_list: {
        parameters: {
            query?: {
                /** @description Must have all of: ?amenities=gym,lift */
                amenities?: string;
                /** @description Multiple values may be separated by commas. */
                area?: string[];
                /** @description Map area: min_lng,min_lat,max_lng,max_lat */
                bbox?: string;
                county?: string;
                /**
                 * @description * `sale` - For Sale
                 *     * `rent` - For Rent
                 *     * `lease` - Commercial Lease
                 */
                deal?: "lease" | "rent" | "sale";
                featured?: boolean;
                /**
                 * @description * `unfurnished` - Unfurnished
                 *     * `semi` - Semi-furnished
                 *     * `furnished` - Furnished
                 */
                furnishing?: "furnished" | "semi" | "unfurnished";
                max_price?: number;
                min_baths?: number;
                min_beds?: number;
                min_price?: number;
                /** @description Multiple values may be separated by commas. */
                neighbourhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Keyword, reference or place name */
                q?: string;
                /**
                 * @description * `newest` - Newest
                 *     * `price_asc` - Price: low to high
                 *     * `price_desc` - Price: high to low
                 */
                sort?: "newest" | "price_asc" | "price_desc";
                /** @description Multiple values may be separated by commas. */
                type?: string[];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyGroup"][];
                };
            };
        };
    };
    properties_similar_list: {
        parameters: {
            query?: {
                /** @description Must have all of: ?amenities=gym,lift */
                amenities?: string;
                /** @description Multiple values may be separated by commas. */
                area?: string[];
                /** @description Map area: min_lng,min_lat,max_lng,max_lat */
                bbox?: string;
                county?: string;
                /**
                 * @description * `sale` - For Sale
                 *     * `rent` - For Rent
                 *     * `lease` - Commercial Lease
                 */
                deal?: "lease" | "rent" | "sale";
                featured?: boolean;
                /**
                 * @description * `unfurnished` - Unfurnished
                 *     * `semi` - Semi-furnished
                 *     * `furnished` - Furnished
                 */
                furnishing?: "furnished" | "semi" | "unfurnished";
                max_price?: number;
                min_baths?: number;
                min_beds?: number;
                min_price?: number;
                /** @description Multiple values may be separated by commas. */
                neighbourhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Keyword, reference or place name */
                q?: string;
                /**
                 * @description * `newest` - Newest
                 *     * `price_asc` - Price: low to high
                 *     * `price_desc` - Price: high to low
                 */
                sort?: "newest" | "price_asc" | "price_desc";
                /** @description Multiple values may be separated by commas. */
                type?: string[];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"][];
                };
            };
        };
    };
    properties_map_list: {
        parameters: {
            query?: {
                /** @description Must have all of: ?amenities=gym,lift */
                amenities?: string;
                /** @description Multiple values may be separated by commas. */
                area?: string[];
                /** @description Map area: min_lng,min_lat,max_lng,max_lat */
                bbox?: string;
                county?: string;
                /**
                 * @description * `sale` - For Sale
                 *     * `rent` - For Rent
                 *     * `lease` - Commercial Lease
                 */
                deal?: "lease" | "rent" | "sale";
                featured?: boolean;
                /**
                 * @description * `unfurnished` - Unfurnished
                 *     * `semi` - Semi-furnished
                 *     * `furnished` - Furnished
                 */
                furnishing?: "furnished" | "semi" | "unfurnished";
                max_price?: number;
                min_baths?: number;
                min_beds?: number;
                min_price?: number;
                /** @description Multiple values may be separated by commas. */
                neighbourhood?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Keyword, reference or place name */
                q?: string;
                /**
                 * @description * `newest` - Newest
                 *     * `price_asc` - Price: low to high
                 *     * `price_desc` - Price: high to low
                 */
                sort?: "newest" | "price_asc" | "price_desc";
                /** @description Multiple values may be separated by commas. */
                type?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapPoint"][];
                };
            };
        };
    };
    property_types_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyType"][];
                };
            };
        };
    };
}
