# Generated by Django 6.1.1 on 2026-10-01 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('kind', models.CharField(choices=[('listing', 'Property enquiry'), ('contact', 'General enquiry'), ('valuation', 'Valuation request'), ('management', 'Property management')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, max_length=3000)),
                ('property_label', models.CharField(blank=True, help_text='Reference and title when sent (kept if deleted).', max_length=200)),
                ('property_type', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('purpose', models.CharField(blank=True, choices=[('mortgage', 'Mortgage or bank loan'), ('sale', 'Selling'), ('purchase', 'Buying'), ('insurance', 'Insurance'), ('probate', 'Probate or succession'), ('other', 'Other')], max_length=20)),
                ('units', models.PositiveSmallIntegerField(blank=True, help_text='Units to manage', null=True)),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('consent_at', models.DateTimeField()),
                ('consent_version', models.CharField(default='2026-10-02', max_length=20)),
                ('spam_check', models.CharField(blank=True, help_text='Turnstile result: passed, unverified (Cloudflare unreachable) or off.', max_length=20)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing', 'Viewing'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('follow_up_on', models.DateField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_spam', models.BooleanField(db_index=True, default=False)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='listings.property')),
                ('user', models.ForeignKey(blank=True, help_text="The visitor's account, if they were signed in.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=5000)),
                ('is_system', models.BooleanField(default=False, help_text='Recorded automatically.')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['is_spam', 'stage', '-created_at'], name='enquiries_e_is_spam_cc473a_idx'),
        ),
    ]
