# Generated by Django 6.1.1 on 2026-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='kind',
            field=models.CharField(choices=[('listing', 'Property enquiry'), ('contact', 'General enquiry'), ('valuation', 'Valuation request'), ('management', 'Property management'), ('assets', 'Asset management'), ('survey', 'Land survey')], db_index=True, max_length=20),
        ),
    ]
